[package]
name = "signature_ecs"
version = "0.1.0"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"

[dependencies.bitset]
version = "0.2.4"
git = "https://github.com/lambdaxymox/bitset"

